import { Assessment, PatientAssessmentSummary } from "@/src/api";

export const DEMO_ASSESSMENT_ID = "rehyn-demo-assessment";

const createdAt = new Date().toISOString();

const clinicalReviewGate = {
  version: "demo-v1",
  status: "clear" as const,
  rehab_access: "allowed" as const,
  rehab_plan_source: "fixed_core_programme",
  reason_code: "demo_sample",
  therapist_confirmation_required: false,
  patient_title: "Sample plan ready",
  patient_message: "This sample shows how Rehyn connects movement findings with practical next steps.",
  next_step: "Explore the sample plan. Your real plan will only use your completed assessment.",
  reporting_rule: "Demonstration data only. This is not a clinical result.",
};
export const demoAssessment: Assessment = {
  id: DEMO_ASSESSMENT_ID,
  created_at: createdAt,
  affected_side: "right",
  assessment_package: "initial",
  patient_parameters: { age_band: "70-79" },
  functional_issues: [
    {
      code: "DEMO_SHOULDER_EFFORT",
      label: "Higher right shoulder effort during reaching",
      description: "The sample movement pattern used more shoulder effort than the matched pattern.",
      source: "Demonstration musculoskeletal model",
      severity: "moderate",
      related_task: "T1",
      related_step: "T1-S1",
      phenotype_domain: "upper_limb",
    },
  ],
  rehab_plan: [
    {
      id: "ex_trunk",
      name: "Trunk-Restrained Reaching",
      description: "Sit with a strap or chair-back contact to limit trunk motion. Reach forward using only the arm.",
      sets: 3,
      reps: 10,
      frequency: "Daily",
      targets_issue: "TRUNK_COMP",
      source: "Levin & Michaelsen (2008)",
      selection_reason: "Included in Rehyn's current four-exercise core programme.",
      safety_note: "Use a stable seated position and a comfortable, pain-free range.",
      requires_clinician_confirmation: false,
    },
    {
      id: "ex_reach",
      name: "Graded Forward Reach",
      description: "Sit upright. Reach toward a target placed progressively farther forward, then return slowly.",
      sets: 3,
      reps: 10,
      frequency: "Twice daily",
      targets_issue: "REACH_INCOMPLETE",
      source: "Task-Specific Training (Carr & Shepherd)",
      selection_reason: "Included in Rehyn's current four-exercise core programme.",
      safety_note: "Use a stable seated position and a comfortable, pain-free range.",
      requires_clinician_confirmation: false,
    },
    {
      id: "ex_grasp",
      name: "Cylindrical Grasp & Transport",
      description: "Reach to the virtual cup, carry it across the midline with your hand, and set it down at the target.",
      sets: 3,
      reps: 10,
      frequency: "Twice daily",
      targets_issue: "GROSS_GRASP",
      source: "ARAT-based functional retraining",
      selection_reason: "Included in Rehyn's current four-exercise core programme.",
      safety_note: "Use a stable seated position and a comfortable, pain-free range.",
      requires_clinician_confirmation: false,
    },
    {
      id: "ex_h2m",
      name: "Hand-to-Mouth ADL Practice",
      description: "Bring the virtual cup to your mouth with the affected hand, focusing on smooth elbow flexion.",
      sets: 3,
      reps: 10,
      frequency: "Twice daily",
      targets_issue: "H2M_IMPAIRED",
      source: "Occupational Therapy ADL retraining",
      selection_reason: "Included in Rehyn's current four-exercise core programme.",
      safety_note: "Use a stable seated position and a comfortable, pain-free range.",
      requires_clinician_confirmation: false,
    },
  ],
  domain_assessments: [
    { domain: "upper_limb", label: "Upper limb", task_count: 3, completed_steps: 6, total_steps: 6, completion_percent: 100, interpretation: "Right shoulder effort was higher during reaching.", method: "Demo modeled estimate", clinical_status: "sample" },
    { domain: "hand", label: "Hand function", task_count: 3, completed_steps: 6, total_steps: 6, completion_percent: 100, interpretation: "Hand opening and closing appeared controlled in this sample.", method: "Demo movement observation", clinical_status: "sample" },
    { domain: "lower_limb", label: "Lower limb", task_count: 1, completed_steps: 2, total_steps: 2, completion_percent: 100, interpretation: "Walking appeared steady in this sample.", method: "Demo gait observation", clinical_status: "sample" },
  ],
  clinician_measures: [],
  biomechanical_estimates: [],
  measurement_form: {
    version: "demo-v1",
    reporting_rule: "Demonstration data only.",
    summary: { auto_filled: 2, model_filled: 0, clinician_filled: 0, tool_filled: 0, pending: 0 },
    domains: [
      {
        domain: "upper_limb",
        label: "Upper limb",
        auto_filled: 2,
        model_filled: 0,
        clinician_filled: 0,
        tool_filled: 0,
        pending: 0,
        rows: [
          { code: "UL_SHOULDER_ELEVATION", label: "Arm elevation", scale: "demo", source_type: "camera", source_label: "Sample camera estimate", status: "sample", value: 72, unit: "deg", method: "Sample pose estimate", confidence: "demo", requirement: "Completed reaching task", applicable_to_submitted_tasks: true },
          { code: "UL_TRUNK_COMPENSATION", label: "Trunk movement", scale: "demo", source_type: "camera", source_label: "Sample camera estimate", status: "sample", value: 9, unit: "deg", method: "Sample pose estimate", confidence: "demo", requirement: "Completed reaching task", applicable_to_submitted_tasks: true },
        ],
      },
    ],
    scale_readiness: [],
  },
  clinical_review_gate: clinicalReviewGate,
};

export const demoPatientAssessmentSummary: PatientAssessmentSummary = {
  id: DEMO_ASSESSMENT_ID,
  created_at: createdAt,
  assessment_package: "initial",
  collection: {
    tasks_collected: 7,
    tasks_expected: 7,
    completed_steps: 14,
    total_steps: 14,
    completion_percent: 100,
    duration_ms: 178000,
    domains: [
      { domain: "upper_limb", label: "Upper limb" },
      { domain: "hand", label: "Hand function" },
      { domain: "lower_limb", label: "Lower limb" },
    ],
  },
  body_function_summary: {
    version: "demo-v1",
    overall_status: "review_recommended",
    model_analysis_complete: true,
    domains: [
      { domain: "upper_limb", label: "Upper limb", status: "review_recommended", tasks_completed: 3, tasks_observed: 3, step_completion_percent: 100, average_task_duration_ms: 24000, findings_count: 1, summary: "Reaching was completed, with more effort around the right shoulder than the matched sample pattern." },
      { domain: "hand", label: "Hand function", status: "no_observable_difficulty", tasks_completed: 3, tasks_observed: 3, step_completion_percent: 100, average_task_duration_ms: 18000, findings_count: 0, summary: "Hand opening and closing appeared controlled in the observed sample tasks." },
      { domain: "lower_limb", label: "Lower limb", status: "no_observable_difficulty", tasks_completed: 1, tasks_observed: 1, step_completion_percent: 100, average_task_duration_ms: 52000, findings_count: 0, summary: "The sample walking pattern appeared steady with evenly timed steps." },
    ],
    reporting_rule: "Demonstration data only. Your real snapshot will use your own recordings and analysis.",
  },
  movement_snapshot_decision: {
    version: "demo-v1",
    status: "finding_selected",
    affected_side: "right",
    step_outcomes: [],
    triggered_thresholds: [
      {
        task_id: "T1",
        source: "task",
        metric: "shoulder_demand_ratio",
        observed: 1.3,
        operator: ">",
        threshold: 1,
        finding_code: "DEMO_SHOULDER_EFFORT",
      },
    ],
    functional_findings: [
      {
        code: "DEMO_SHOULDER_EFFORT",
        label: "The right shoulder used more effort than the matched reaching pattern.",
        severity: "moderate",
        related_task: "T1",
        related_step: "T1-S1",
        phenotype_domain: "upper_limb",
        category: "upper_limb",
      },
    ],
    body_function_domains: [
      { domain: "upper_limb", status: "review_recommended", findings_count: 1, step_completion_percent: 100 },
      { domain: "hand", status: "no_observable_difficulty", findings_count: 0, step_completion_percent: 100 },
      { domain: "lower_limb", status: "no_observable_difficulty", findings_count: 0, step_completion_percent: 100 },
    ],
    model_status: {
      overall: "research_ready",
      gpu_stage: { status: "demo_sample" },
      musculoskeletal_stage: { status: "demo_sample" },
    },
    primary_finding: {
      code: "DEMO_SHOULDER_EFFORT",
      label: "Higher right shoulder effort during reaching",
      category: "upper_limb",
    },
    selection_rule: {
      strategy: "Use the primary task-specific functional finding.",
      candidate_issue_codes: ["DEMO_SHOULDER_EFFORT"],
      selected_issue_code: "DEMO_SHOULDER_EFFORT",
      no_issue_sentinel_excluded: true,
    },
    presentation: {
      eyebrow: "RIGHT SHOULDER",
      title: "Your right shoulder may need support when reaching",
      summary: "Reaching, lifting, or placing everyday objects may require more effort.",
      tone: "attention",
    },
    anatomy_marker: {
      visible: true,
      region: "right_shoulder",
      side: "right",
      source_issue_code: "DEMO_SHOULDER_EFFORT",
      coordinate_source: "age-specific anatomy shoulder anchor",
      reason: "The sample reaching finding is located at the right shoulder.",
    },
  },
  functional_metrics: {
    shoulder_flexion_deg: 72,
    trunk_lean_deg: 9,
    reach_completion: 100,
    bilateral_symmetry: 88,
    pinch_grip: 92,
    hand_opening: 94,
    walking_skipped: false,
    domains: {
      upper_limb: {
        observed: true,
        step_completion_percent: 100,
        shoulder_elevation_deg: 72,
        trunk_lean_deg: 9,
        shoulder_hike_detected: true,
      },
      hand: {
        observed: true,
        step_completion_percent: 100,
        hand_opening_percent: 94,
        pinch_control_percent: 92,
      },
      lower_limb: {
        observed: true,
        skipped: false,
        step_completion_percent: 100,
        bilateral_motion_symmetry_percent: 88,
        full_body_visibility_percent: 96,
        video_duration_seconds: 7,
      },
    },
  },
  rehab_plan_ready: true,
  clinical_review_gate: clinicalReviewGate,
  insights: {
    version: "demo-v1",
    status: "research_ready",
    badge: "Demo result",
    headline: "Walking looked steady. Your right shoulder may benefit from support during reaching.",
    summary: "Your walking pattern appeared steady, while the sample reach placed more demand on the right shoulder. This is an example of the story Rehyn creates from a completed assessment.",
    domain_metrics: [
      { domain: "upper_limb", label: "Right shoulder", completion_percent: 100, findings_count: 1, status: "review_recommended" },
      { domain: "hand", label: "Hand function", completion_percent: 100, findings_count: 0, status: "no_observable_difficulty" },
      { domain: "lower_limb", label: "Walking", completion_percent: 100, findings_count: 0, status: "no_observable_difficulty" },
    ],
    activation_profile: [
      { task_id: "T1", domain: "upper_limb", muscle: "deltoid_anterior_r", label: "Right anterior deltoid", mean: 0.52, peak: 0.71, template_mean: 0.4, delta_mean: 0.12 },
      { task_id: "T4", domain: "hand", muscle: "finger_extensors_r", label: "Right finger extensors", mean: 0.34, peak: 0.48, template_mean: 0.35, delta_mean: -0.01 },
      { task_id: "T7", domain: "lower_limb", muscle: "quadriceps_r", label: "Right quadriceps", mean: 0.41, peak: 0.58, template_mean: 0.42, delta_mean: -0.01 },
    ],
    modeled_domains: ["upper_limb", "hand", "lower_limb"],
    observations: [
      { title: "Your right shoulder worked harder", detail: "The sample reach used about 1.3 times the matched shoulder demand." },
      { title: "Walking looked steady", detail: "Step timing was even throughout the sample walking observation." },
    ],
    analysis_order: ["task_collection", "musculoskeletal_analysis", "patient_insights", "rehab_plan"],
    reporting_rule: "This sample is for product demonstration and is not a diagnosis or patient result.",
  },
};
